# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install production dependencies (skip prepare scripts), then install dev tools for build
RUN npm install --production --ignore-scripts \
    && npm install typescript @types/node --no-save \
    && npm run build

# Remove source files after build to slim image
RUN rm -rf src

# Set environment defaults
ENV NODE_ENV=production \
    SAVE_TO_DESKTOP=false \
    DEBUG=false

# Expose no ports (stdio transport)

# Start the MCP server
ENTRYPOINT ["node", "build/run.mjs"]
